name: CI

on: push

jobs:
  build_macos:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Installs deps
      run: brew install --only-dependencies ./Formula/hugo-unix.rb

    - name: Build
      run: brew reinstall --verbose --build-from-source ./Formula/hugo-unix.rb

    - name: Test
      run: |
        brew test ./Formula/hugo-unix.rb
        brew audit --strict ./Formula/hugo-unix.rb
        brew style ./Formula/hugo-unix.rb
